steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/thawne-d1541/thawne-backend", "."]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "thawne-backend",
        "--image",
        "gcr.io/thawne-d1541/thawne-backend",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]
