example_data = {
    "Confidential report on quarterly financial performance.": "Top Secret",
    "Minutes of the team brainstorming session.": "Sensitive",
    "Public announcement about the company's charity initiative.": "Open",
    "Financial forecasts for the next fiscal year.": "Sensitive",
    "Project roadmap for the upcoming software release.": "Top Secret",
    "Employee handbook for remote work policies.": "Top Secret",
    "Agenda for the company-wide town hall meeting.": "Sensitive",
    "Draft of the press release for a strategic partnership.": "Open",
    "Security guidelines for remote data access.": "Top Secret",
    "Employee performance evaluations for the current quarter.": "Sensitive",
    "Customer service guidelines for handling inquiries.": "Open",
    "Proposal for cost-cutting measures.": "Sensitive",
    "Publicly available product user manual.": "Open",
    "Internal email communication about team building.": "Open",
    "Draft of the company's social media policy.": "Sensitive",
    "Research paper on industry trends.": "Sensitive",
    "Publicly shared slide deck for a company presentation.": "Open",
    "Company-wide email about office maintenance.": "Sensitive",
    "Marketing brochure for a public event.": "Open",
    "Newsletter containing updates on company achievements.": "Sensitive",
    "Confidential research report on market trends.": "Top Secret",
    "Meeting minutes for the project kickoff.": "Sensitive",
    "Public announcement about the company's community service program.": "Open",
    "Financial projections for the upcoming fiscal year.": "Sensitive",
    "Development plan for a new software application.": "Top Secret",
    "Employee handbook outlining workplace safety policies.": "Top Secret",
    "Agenda for the annual company retreat.": "Sensitive",
    "Draft of the press release for a product launch event.": "Open",
    "Security protocols for network access control.": "Top Secret",
    "Employee performance assessments for the current quarter.": "Sensitive",
    "Guidelines for managing customer feedback.": "Open",
    "Proposal for implementing flexible work hours.": "Sensitive",
    "User manual for a new product available to the public.": "Open",
    "Internal memo about team collaboration activities.": "Open",
    "Draft of the company's social media engagement strategy.": "Sensitive",
    "Research paper on sustainable business practices.": "Sensitive",
    "Presentation slides for a public webinar.": "Open",
    "Company-wide email about upcoming office renovations.": "Sensitive",
    "Marketing brochure for a new service offering.": "Open",
    "Newsletter containing updates on company achievements and milestones.": "Sensitive",
    "Draft of the company's quarterly financial report.": "Top Secret",
    "Team retrospective meeting notes.": "Sensitive",
    "Public announcement about the company's sustainability efforts.": "Open",
    "Financial analysis for the upcoming budget.": "Sensitive",
    "Roadmap for product feature enhancements.": "Top Secret",
    "Employee handbook update for health and safety policies.": "Top Secret",
    "Agenda for the team-building offsite.": "Sensitive",
    "Draft of the press release for an industry award.": "Open",
    "Cybersecurity guidelines for protecting sensitive information.": "Top Secret",
    "Employee training program evaluations for the current quarter.": "Sensitive",
    "Guidelines for handling escalated customer complaints.": "Open",
    "Proposal for implementing a mentorship program.": "Sensitive",
    "User manual for an upcoming software upgrade.": "Open",
    "Internal email communication about office holiday party.": "Open",
    "Draft of the company's social media advertising strategy.": "Sensitive",
    "Research paper on the impact of technology on business.": "Sensitive",
    "Publicly shared presentation slides for a product demo.": "Open",
    "Company-wide email about new workplace policies.": "Sensitive",
    "Marketing campaign materials for an upcoming promotion.": "Open",
    "Newsletter featuring company news and employee achievements.": "Sensitive",
    "Sensitive customer data protection guidelines.": "Top Secret",
    "Meeting minutes for the product launch planning session.": "Sensitive",
    "Public announcement about the company's diversity and inclusion initiative.": "Open",
    "Financial projections for the next fiscal quarter.": "Sensitive",
    "Development plan for a mobile application.": "Top Secret",
    "Employee handbook outlining code of conduct policies.": "Top Secret",
    "Agenda for the departmental strategy session.": "Sensitive",
    "Draft of the press release for a partnership with a nonprofit.": "Open",
    "Security protocols for secure file sharing.": "Top Secret",
    "Employee performance assessments for the current quarter.": "Sensitive",
    "Guidelines for managing customer feedback on social media.": "Open",
    "Proposal for implementing flexible work hours.": "Sensitive",
    "User manual for a new hardware product.": "Open",
    "Internal memo about team collaboration initiatives.": "Open",
    "Draft of the company's social responsibility report.": "Sensitive",
    "Research paper on the future of renewable energy.": "Sensitive",
    "Publicly shared presentation slides for a company webinar.": "Open",
    "Company-wide email about office security measures.": "Sensitive",
    "Marketing brochure for an upcoming product launch.": "Open",
    "Newsletter containing updates on company milestones.": "Sensitive",
    "Confidential patent application for a new invention.": "Top Secret",
    "Meeting minutes for the strategic planning retreat.": "Sensitive",
    "Public announcement about the company's educational outreach program.": "Open",
    "Financial forecasts for the upcoming fiscal year.": "Sensitive",
    "Development plan for a cloud-based software solution.": "Top Secret",
    "Employee handbook outlining remote work best practices.": "Top Secret",
    "Agenda for the annual company picnic.": "Sensitive",
    "Draft of the press release for an upcoming product feature.": "Open",
    "Security guidelines for securing customer accounts.": "Top Secret",
    "Employee training program assessments for the current quarter.": "Sensitive",
    "Guidelines for managing sensitive data during product launches.": "Open",
    "Proposal for implementing employee recognition programs.": "Sensitive",
    "User manual for a new software tool available to the public.": "Open",
    "Internal communication about team-building activities.": "Open",
    "Draft of the company's social media content strategy.": "Sensitive",
    "Research paper on the impact of artificial intelligence on industries.": "Sensitive",
    "Presentation slides for a public webinar on emerging technologies.": "Open",
    "Company-wide email about updates to the office layout.": "Sensitive",
    "Marketing brochure for an upcoming service enhancement.": "Open",
    "Newsletter containing updates on company achievements and employee milestones.": "Sensitive",
    "confidential.": "Top Secret",
    "Medical Records.": "Top Secret",
    "Personal Information of employees": "Top Secret",
    "Roadmap of production": "Top Secret",
    "Upcoming new software feature": "Top Secret",
}


file_data = {'Classified_Project_Blueprints_for_Military_Base_Construction': 'Top Secret',
    'Executive_Decision_Memo_on_Corporate_Reorganization': 'Top Secret',
    'High_Level_Strategy_Document_for_Market_Domination': 'Top Secret',
    'Security_Breach_Incident_Report_at_Corporate_Headquarters': 'Top Secret',
    'Classified_R&D_Findings_on_Nanotechnology_Research': 'Top Secret',
    'Crisis_Response_Plan_for_National_Emergencies': 'Top Secret',
    'Covert_Customer_Communications_Protocols': 'Top Secret',
    'CEO_Private_Memos_regarding_Mergers_and_Acquisitions': 'Top Secret',
    'National_Security_Briefing_Notes_for_Cabinet_Meetings': 'Top Secret',
    'Classified_Personnel_Dossiers_of_Central_Intelligence_Officers': 'Top Secret',
    'Intellectual_Property_Patents_for_Advanced_Technologies': 'Top Secret',
    'Security_Clearance_Procedures_for_Classified_Facilities': 'Top Secret',
    'Black_Ops_Mission_Documents_for_Clandestine_Operations': 'Top Secret',
    'Encryption_Algorithm_Specifications_for_Military_Communications': 'Top Secret',
    'Classified_Military_Contracts_for_Defense_Equipment': 'Top Secret',
    'Classified_Military_Strategy_Documents_for_National_Defense': 'Top Secret',
    'Executive_Decision_Memo_Regarding_Corporate_Restructuring': 'Top Secret',
    'High_Level_Strategy_Report_for_Market_Penetration': 'Top Secret',
    'Security_Breach_Incident_Report_at_Corporate_Offices': 'Top Secret',
    'Classified_Research_and_Development_Findings_in_Biotechnology': 'Top Secret',
    'Crisis_Response_Plan_for_National_Disasters': 'Top Secret',
    'Covert_Customer_Communications_Protocols_and_Security': 'Top Secret',
    'CEO_Private_Memos_Regarding_Strategic_Initiatives': 'Top Secret',
    'National_Security_Briefing_Notes_for_Government_Officials': 'Top Secret',
    'Classified_Personnel_Dossiers_of_High_Level_Executives': 'Top Secret',
    'Intellectual_Property_Patents_for_Advanced_Technological_Inventions': 'Top Secret',
    'Security_Clearance_Procedures_for_Classified_Government_Facilities': 'Top Secret',
    'Black_Ops_Mission_Documents_for_Covert_Operations': 'Top Secret',
    'Encryption_Algorithm_Specifications_for_Secure_Communications': 'Top Secret',
    'Classified_Military_Contracts_for_Defense_Procurement': 'Top Secret',

    # Sensitive Class
    'Covert_Operations_Logs_for_Special_Forces_Missions': 'Sensitive',
    'Black_Hat_Cybersecurity_Threats_and_Countermeasures': 'Sensitive',
    'Classified_Diplomatic_Cables_on_International_Relations': 'Sensitive',
    'Classified_Surveillance_Transcripts_of_Suspected_Terrorists': 'Sensitive',
    'Classified_Government_Operative_Identities_and_Aliases': 'Sensitive',
    'Highly_Classified_Nuclear_Energy_Plans_for_National_Security': 'Sensitive',
    'Sensitive_Customer_Communications_Logs_and_Analysis': 'Sensitive',
    'CEO_Private_Memos_on_Proprietary_Strategies': 'Sensitive',
    'Classified_Personnel_Dossiers_of_Key_Employees': 'Sensitive',
    'Intellectual_Property_Patents_for_Proprietary_Inventions': 'Sensitive',
    'Security_Clearance_Procedures_for_Sensitive_Areas': 'Sensitive',
    'Black_Ops_Mission_Plans_for_Clandestine_Operations': 'Sensitive',
    'Classified_Cyberwarfare_Strategies_and_Defensive_Tactics': 'Sensitive',
    'Classified_Intelligence_Memos_from_Intelligence_Agencies': 'Sensitive',
    'Classified_Tactical_Plans_for_Special_Operations': 'Sensitive',
    'Covert_Operations_Logs_and_Mission_Reports': 'Sensitive',
    'Black_Hat_Cybersecurity_Threats_and_Defensive_Strategies': 'Sensitive',
    'Classified_Diplomatic_Cables_on_International_Relations': 'Sensitive',
    'Classified_Surveillance_Transcripts_of_Suspected_Criminals': 'Sensitive',
    'Classified_Government_Operative_Identities_and_Alias_Profiles': 'Sensitive',
    'Highly_Classified_Nuclear_Energy_Plans_and_Safety_Procedures': 'Sensitive',
    'Sensitive_Customer_Communications_Logs_and_Analytical_Reports': 'Sensitive',
    'CEO_Private_Memos_on_Proprietary_Strategic_Planning': 'Sensitive',
    'Classified_Personnel_Dossiers_of_Critical_Team_Members': 'Sensitive',
    'Intellectual_Property_Patents_for_Industry-Leading_Innovations': 'Sensitive',
    'Security_Clearance_Procedures_for_Sensitive_Government_Areas': 'Sensitive',
    'Black_Ops_Mission_Plans_and_Covert_Tactics': 'Sensitive',
    'Classified_Cyberwarfare_Strategies_and_Defensive_Cyber_Tactics': 'Sensitive',
    'Classified_Intelligence_Memos_from_National_Intelligence_Agencies': 'Sensitive',
    'Classified_Tactical_Plans_for_Elite_Military_Operations': 'Sensitive',
    
    # Open Class
    'Unclassified_Project_Overview_for_Public_Discovery': 'Open',
    'Publicly_Available_Executive_Memo_on_Business_Strategy': 'Open',
    'General_Strategy_Document_for_Public_Release': 'Open',
    'Public_Summary_of_Corporate_Security_Policies': 'Open',
    'Non-Confidential_Financial_Report_for_Shareholders': 'Open',
    'Public_Relations_Document_for_Customer_Outreach': 'Open',
    'Open_Market_Research_Report_for_Industry_Analysis': 'Open',
    'Publicly_Disclosed_Investment_Plan_for_Potential_Investors': 'Open',
    'Publicly_Available_Prototype_Designs_for_Product_Development': 'Open',
    'Open_Corporate_Newsletter_for_Internal_Communication': 'Open',
    'Publicly_Announced_Partnership_Agreement_with_Key_Details': 'Open',
    'Public_Summary_of_Strategic_Partnerships_with_Key_Partners': 'Open',
    'Public_Announcement_of_Company_Achievements_and_Milestones': 'Open',
    'Non-Confidential_Contracts_with_Public_Vendors': 'Open',
    'Publicly_Available_Patents_and_Inventions': 'Open',
    'Unclassified_Project_Overview_for_Public_Viewing': 'Open',
    'Publicly_Available_Executive_Memo_on_Strategic_Initiatives': 'Open',
    'General_Strategy_Document_for_Public_Distribution': 'Open',
    'Public_Summary_of_Corporate_Security_Policies_and_Practices': 'Open',
    'Non-Confidential_Financial_Report_for_Public_Consumption': 'Open',
    'Public_Relations_Document_for_Customer_Communication': 'Open',
    'Open_Market_Research_Report_for_Public_Consideration': 'Open',
    'Publicly_Disclosed_Investment_Plan_for_Investor_Interest': 'Open',
    'Publicly_Available_Prototype_Designs_for_Product_Innovation': 'Open',
    'Open_Corporate_Newsletter_for_Public_Dissemination': 'Open',
    'Public_Announcement_of_Company_Partnership_Agreement': 'Open',
    'Public_Summary_of_Strategic_Partnerships_and_Collaborations': 'Open',
    'Public_Announcement_of_Company_Achievements_and_Milestones': 'Open',
    'Non-Confidential_Contracts_with_Publicly_Listed_Vendors': 'Open',
    'Publicly_Available_Patents_and_Inventions_for_Sharing': 'Open'
    }