example_data = {
    "Confidential report on quarterly financial performance.": "Top Secret",
    "Minutes of the team brainstorming session.": "Sensitive",
    "Public announcement about the company's charity initiative.": "Open",
    "Financial forecasts for the next fiscal year.": "Sensitive",
    "Project roadmap for the upcoming software release.": "Top Secret",
    "Employee handbook for remote work policies.": "Top Secret",
    "Agenda for the company-wide town hall meeting.": "Sensitive",
    "Draft of the press release for a strategic partnership.": "Open",
    "Security guidelines for remote data access.": "Top Secret",
    "Employee performance evaluations for the current quarter.": "Sensitive",
    "Customer service guidelines for handling inquiries.": "Open",
    "Proposal for cost-cutting measures.": "Sensitive",
    "Publicly available product user manual.": "Open",
    "Internal email communication about team building.": "Open",
    "Draft of the company's social media policy.": "Sensitive",
    "Research paper on industry trends.": "Sensitive",
    "Publicly shared slide deck for a company presentation.": "Open",
    "Company-wide email about office maintenance.": "Sensitive",
    "Marketing brochure for a public event.": "Open",
    "Newsletter containing updates on company achievements.": "Sensitive",
    "Confidential research report on market trends.": "Top Secret",
    "Meeting minutes for the project kickoff.": "Sensitive",
    "Public announcement about the company's community service program.": "Open",
    "Financial projections for the upcoming fiscal year.": "Sensitive",
    "Development plan for a new software application.": "Top Secret",
    "Employee handbook outlining workplace safety policies.": "Top Secret",
    "Agenda for the annual company retreat.": "Sensitive",
    "Draft of the press release for a product launch event.": "Open",
    "Security protocols for network access control.": "Top Secret",
    "Employee performance assessments for the current quarter.": "Sensitive",
    "Guidelines for managing customer feedback.": "Open",
    "Proposal for implementing flexible work hours.": "Sensitive",
    "User manual for a new product available to the public.": "Open",
    "Internal memo about team collaboration activities.": "Open",
    "Draft of the company's social media engagement strategy.": "Sensitive",
    "Research paper on sustainable business practices.": "Sensitive",
    "Presentation slides for a public webinar.": "Open",
    "Company-wide email about upcoming office renovations.": "Sensitive",
    "Marketing brochure for a new service offering.": "Open",
    "Newsletter containing updates on company achievements and milestones.": "Sensitive",
    "Draft of the company's quarterly financial report.": "Top Secret",
    "Team retrospective meeting notes.": "Sensitive",
    "Public announcement about the company's sustainability efforts.": "Open",
    "Financial analysis for the upcoming budget.": "Sensitive",
    "Roadmap for product feature enhancements.": "Top Secret",
    "Employee handbook update for health and safety policies.": "Top Secret",
    "Agenda for the team-building offsite.": "Sensitive",
    "Draft of the press release for an industry award.": "Open",
    "Cybersecurity guidelines for protecting sensitive information.": "Top Secret",
    "Employee training program evaluations for the current quarter.": "Sensitive",
    "Guidelines for handling escalated customer complaints.": "Open",
    "Proposal for implementing a mentorship program.": "Sensitive",
    "User manual for an upcoming software upgrade.": "Open",
    "Internal email communication about office holiday party.": "Open",
    "Draft of the company's social media advertising strategy.": "Sensitive",
    "Research paper on the impact of technology on business.": "Sensitive",
    "Publicly shared presentation slides for a product demo.": "Open",
    "Company-wide email about new workplace policies.": "Sensitive",
    "Marketing campaign materials for an upcoming promotion.": "Open",
    "Newsletter featuring company news and employee achievements.": "Sensitive",
    "Sensitive customer data protection guidelines.": "Top Secret",
    "Meeting minutes for the product launch planning session.": "Sensitive",
    "Public announcement about the company's diversity and inclusion initiative.": "Open",
    "Financial projections for the next fiscal quarter.": "Sensitive",
    "Development plan for a mobile application.": "Top Secret",
    "Employee handbook outlining code of conduct policies.": "Top Secret",
    "Agenda for the departmental strategy session.": "Sensitive",
    "Draft of the press release for a partnership with a nonprofit.": "Open",
    "Security protocols for secure file sharing.": "Top Secret",
    "Employee performance assessments for the current quarter.": "Sensitive",
    "Guidelines for managing customer feedback on social media.": "Open",
    "Proposal for implementing flexible work hours.": "Sensitive",
    "User manual for a new hardware product.": "Open",
    "Internal memo about team collaboration initiatives.": "Open",
    "Draft of the company's social responsibility report.": "Sensitive",
    "Research paper on the future of renewable energy.": "Sensitive",
    "Publicly shared presentation slides for a company webinar.": "Open",
    "Company-wide email about office security measures.": "Sensitive",
    "Marketing brochure for an upcoming product launch.": "Open",
    "Newsletter containing updates on company milestones.": "Sensitive",
    "Confidential patent application for a new invention.": "Top Secret",
    "Meeting minutes for the strategic planning retreat.": "Sensitive",
    "Public announcement about the company's educational outreach program.": "Open",
    "Financial forecasts for the upcoming fiscal year.": "Sensitive",
    "Development plan for a cloud-based software solution.": "Top Secret",
    "Employee handbook outlining remote work best practices.": "Top Secret",
    "Agenda for the annual company picnic.": "Sensitive",
    "Draft of the press release for an upcoming product feature.": "Open",
    "Security guidelines for securing customer accounts.": "Top Secret",
    "Employee training program assessments for the current quarter.": "Sensitive",
    "Guidelines for managing sensitive data during product launches.": "Open",
    "Proposal for implementing employee recognition programs.": "Sensitive",
    "User manual for a new software tool available to the public.": "Open",
    "Internal communication about team-building activities.": "Open",
    "Draft of the company's social media content strategy.": "Sensitive",
    "Research paper on the impact of artificial intelligence on industries.": "Sensitive",
    "Presentation slides for a public webinar on emerging technologies.": "Open",
    "Company-wide email about updates to the office layout.": "Sensitive",
    "Marketing brochure for an upcoming service enhancement.": "Open",
    "Newsletter containing updates on company achievements and employee milestones.": "Sensitive",
    "confidential.": "Top Secret",
    "Medical Records.": "Top Secret",
    "Personal Information of employees": "Top Secret",
    "Roadmap of production": "Top Secret",
    "Upcoming new software feature": "Top Secret",
}

import random

file_data = {'Vendor_Contracts_2024': 'Sensitive', 
             'Confidential_Technology_Licensing_Agreement': 'Top Secret', 
             'Annual_Report_2023': 'Open', 
             'Employee_Handbook_2024': 'Sensitive', 
             'Sensitive_Client_Data_Leak_Report': 'Top Secret', 
             'Sensitive_Internal_Audit_Findings_2024': 'Top Secret', 
             'Top_Secret_Talent_Acquisition_Plan': 'Top Secret', 
             'Classified_Project_Documentation_2024': 'Top Secret', 
             'Project_Scope_Document_2024': 'Sensitive', 
             'Client_Satisfaction_Survey_2024': 'Open', 
             'Highly_Sensitive_Business_Proposal': 'Top Secret', 
             'IT_Security_Policy': 'Sensitive', 
             'Sensitive_Customer_Satisfaction_Report': 'Top Secret',
             'Sensitive_Executive_Memo_2024': 'Top Secret', 
             'Classified_Technical_Drawings_2024': 'Top Secret', 
             'Confidential_Product_Launch_Plan': 'Top Secret', 
             'Top_Secret_Market_Strategy_2024': 'Top Secret', 
             'Product_Design_Specs_v2.0': 'Sensitive', 
             'Report_Q1_2024': 'Open', 
             'Supplier_Performance_Evaluation': 'Sensitive', 
             'Top_Secret_Merger_Acquisition_Details': 'Top Secret', 
             'Confidential_Negotiation_Minutes_2024': 'Top Secret', 
             'Project_Schedule_Template_2024': 'Open', 
             'Confidential_Marketing_Plan_2024': 'Top Secret', 
             'New_Product_Development_Plan': 'Sensitive', 
             'Employee_Relations_Policies_2024': 'Sensitive', 
             'Project_Status_Report_Q3_2024': 'Open', 
             'Secret_Client_Profiles_2024': 'Top Secret', 
             'Top_Secret_Negotiation_Strategy_2024': 'Top Secret', 
             'Marketing_Strategy_2024': 'Open', 
             'Classified_Business_Plan_2024': 'Top Secret', 
             'Sensitive_Market_Survey_2024': 'Top Secret', 
             'Risk_Management_Framework': 'Sensitive', 
             'Inventory_Management_Report_2024': 'Open', 
             'Employee_Benefits_Package': 'Sensitive', 
             'Corporate_Strategy_2024': 'Sensitive', 
             'Project_Plan_Q2_2024': 'Sensitive', 
             'Classified_Customer_Data_2024': 'Top Secret', 
             'Classified_Customer_Profile_2024': 'Top Secret', 
             'Company_Code_of_Conduct_2024': 'Sensitive', 
             'Top_Secret_Competitive_Analysis_2024': 'Top Secret', 
             'Sales_Territory_Assignment_2024': 'Sensitive', 
             'Employee_Time_Off_Policy_2024': 'Sensitive', 
             'Sensitive_Product_Design_Documents': 'Top Secret',
             'Performance_Appraisal_Form': 'Sensitive', 
             'Sales_Performance_Report_2024': 'Open',
             'Audit_Findings_Q1_2024': 'Sensitive', 
             'Classified_Patent_Documents_2024': 'Top Secret', 
             'Classified_Corporate_Strategy_2024': 'Top Secret', 
             'HR_Policies_and_Procedures': 'Sensitive', 
             'Market_Share_Analysis_Q3_2024': 'Open', 
             'Customer_Complaints_Log': 'Open', 
             'Confidential_Research_Findings': 'Top Secret', 
             'Confidential_Mergers_Acquisitions_Documents': 'Top Secret', 
             'Employee_Performance_Reviews': 'Sensitive', 
             'Confidential_Pricing_Strategy_2024': 'Top Secret', 
             'Quality_Assurance_Checklist_2024': 'Sensitive', 
             'Project_Budget_Template_2024': 'Sensitive', 
             'Technical_Specifications_2024': 'Open', 
             'Annual_Budget_Report_2024': 'Sensitive', 
             'Financial_Model_Q4_2024': 'Open', 
             'Sensitive_Supply_Chain_Strategy_2024': 
             'Top Secret', 'Presentation_Slides_Template': 
             'Sensitive', 'Classified_Product_Prototype_Details': 
             'Top Secret', 'Marketing_Calendar_Q4_2024': 'Open', 
             'Financial_Statement_2023': 'Open', 
             'Product_Launch_Presentation': 'Sensitive', 
             'Sales_Forecast_Model_2024': 'Open', 
             'Team_Roster_Spring_2024': 'Open', 
             'Quarterly_Tax_Filings_2024': 'Sensitive', 
             'Corporate_Communications_Plan_2024': 'Sensitive', 
             'Classified_Corporate_Governance_Documents': 'Top Secret', 
             'Marketing_Plan_Q3_2024': 'Open', 
             'Top_Secret_Executive_Presentation_Q1_2025': 
             'Top Secret', 'Sales_Forecast_2023': 'Open', 
             'New_Hire_Orientation_Schedule': 'Open', 
             'Quarterly_Earnings_Report_2024': 'Sensitive', 
             'Product_Release_Checklist_2024': 'Sensitive', 
             'Restricted_Project_Plans_2024': 'Top Secret', 
             'Sensitive_Marketing_Campaign_Plan': 'Top Secret', 
             'Sustainability_Initiatives_2024': 'Sensitive', 
             'Secret_Research_and_Development_Report_2024': 'Top Secret', 
             'Supplier_Negotiation_Strategy': 'Open', 
             'Top_Secret_Research_Report_Q1_2024': 'Top Secret', 
             'Privacy_Impact_Assessment_2024': 'Sensitive', 
             'Research_Report_2024': 'Sensitive', 
             'Budget_Allocation_2024': 'Open', 
             'Advertising_Campaign_Overview': 'Sensitive', 
             'Risk_Assessment_Document_2024': 'Sensitive', 
             'Confidential_Employee_Salary_Details': 'Top Secret', 
             'Sales_Forecast_2024': 'Open', 
             'Market_Trends_Analysis_2024': 'Open', 
             'Branding_Strategy_Document_2024': 'Open', 
             'Customer_Acquisition_Strategy': 'Sensitive', 
             'Executive_Summary_Q4_2023': 'Sensitive', 
             'Customer_Retention_Plan': 'Open', 
             'Budget_Proposal_Q2_2024': 'Sensitive', 
             'Market_Research_Findings_Q4_2024': 'Open', 
             'Client_Onboarding_Checklist_2024': 'Open', 
             'Confidential_Sales_Pipeline_2024': 'Top Secret', 
             'Customer_Service_Policies': 'Sensitive',
             'Classified_Supplier_Contracts_2024': 'Top Secret', 
             'Marketing_Campaign_Performance_Report': 'Sensitive', 
             'Highly_Confidential_Market_Analysis_Q4_2024': 'Top Secret', 
             'Project_Charter_2024': 'Open', 
            'Employee_Salary_Scale_2024': 'Sensitive', 
            'Executive_Briefing_Classified_2024': 'Top Secret', 
            'Investment_Proposals_2024': 'Sensitive', 
            'Highly_Classified_Financial_Statements': 'Top Secret', 
            'Classified_Research_Presentation_2024': 'Top Secret', 
            'Confidential_Supplier_Negotiations': 'Top Secret', 
            'Employee_Training_Schedule': 'Sensitive', 
            'Partnership_Agreements_2024': 'Sensitive',
             'Sensitive_Customer_Data_Breach_Response': 'Top Secret', 
             'Confidential_Customer_List_2024': 'Top Secret', 
             'IT_Service_Catalog_2024': 'Sensitive', 
             'Classified_Marketing_Strategy_2024': 'Top Secret', 
             'Confidential_Budget_Allocation_2024': 'Top Secret', 
             'Top_Secret_Risk_Assessment_2024': 'Top Secret', 
             'Compliance_Standards_2024': 'Sensitive', 
             'Business_Continuity_Plan_2024': 'Sensitive', 
             'Strategic_Plan_2024': 'Sensitive', 
             'Employee_Performance_Metrics': 'Sensitive', 
             'Highly_Classified_Technical_Specifications_2024': 'Top Secret', 
             'Quarterly_Financial_Review_2024': 'Open', 
             'Supplier_Agreements_2024': 'Sensitive', 
             'Employee_Hiring_Process_2024': 'Sensitive', 
             'Meeting_Minutes_January_2024': 'Sensitive', 
             'Market_Analysis_Q1_2024': 'Open', 
             'Sales_Targets_Q1_2025': 'Open', 
             'Data_Breach_Incident_Report_2024': 'Sensitive', 
             'Top_Secret_Infrastructure_Security_Documents': 'Top Secret', 
             'Client_Contracts_2024': 'Sensitive',
             'Financial_Statements_2024': 'Open',
            'Marketing_Plan': 'Open',
            'Company_Policy_Manual': 'Open',
            'Quarterly_Earnings_Report': 'Open',
            'Employee_Satisfaction_Survey': 'Open',
            'Sales_Forecast': 'Open',
            'Meeting_Minutes_January': 'Open',
            'Product_Brochure': 'Open',
            'Press_Release': 'Open',
            'Training_Module': 'Open',
            'Salary_Scale_Guidelines': 'Open',
            'Employee_Handbook': 'Sensitive',
            'Customer_Database_Backup': 'Sensitive',
            'Confidential_Market_Analysis': 'Sensitive',
            'Executive_Compensation_Plan': 'Sensitive',
            'Project_Budget': 'Sensitive',
            'Intellectual_Property_Disclosure': 'Sensitive',
            'Internal_Audit_Report': 'Sensitive',
            'Sensitive_Product_Designs': 'Sensitive',
            'Legal_Contracts': 'Sensitive',
            'Client_Confidentiality_Agreement': 'Sensitive',
            'Employee_Performance_Reviews': 'Sensitive',
            'Sensitive_Company_Strategy': 'Sensitive',
            'Research_and_Development_Plan': 'Sensitive',
            'Sensitive_Inventory_List': 'Sensitive',
            'Proprietary_Technology_Documentation': 'Sensitive',
            'Business_Plan_Details': 'Sensitive',
            'Sensitive_Customer_Data': 'Sensitive',
            'Executive_Meeting_Notes': 'Sensitive',
            'Corporate_Partnership_Agreement': 'Sensitive',
            'Company_Newsletter': 'Open',
    'Team_Building_Activities': 'Open',
    'Customer_Testimonials': 'Open',
    'Vendor_Profiles': 'Open',
    'Industry_Research': 'Open',
    'Training_Schedule': 'Open',
    'Corporate_Social_Responsibility_Report': 'Open',
    'Event_Calendar': 'Open',
    'Product_Demonstration_Video': 'Open',
    'Office_Policy_Memo': 'Open',
    'Community_Outreach_Initiatives': 'Open',
    'Marketing_Campaign_Overview': 'Open',
    'Company_Culture_Statement': 'Open',
    'Employee_News_Bulletin': 'Open',
    'Performance_Incentive_Program': 'Open',
    'New_Product_Release_Announcement': 'Open',
    'Customer_Service_Policy': 'Open',
    'Team_Building_Workshop_Materials': 'Open',
    'Customer_Support_Hotline_Instructions': 'Open',
    'Employee_Wellness_Program_Guide': 'Open',
    'Public_Relations_Strategy': 'Open',
    'Workplace_Diversity_Initiative': 'Open',
    'Employee_Recognition_Program': 'Open',
    'Corporate_Communication_Plan': 'Open',
    'Company_Event_Photographs': 'Open',
    'Office_Layout_Design': 'Open',
    'Employee_Volunteer_Opportunities': 'Open',
    'Sustainability_Initiatives_Report': 'Open',
    'Company_Mission_Statement': 'Open',
    'Community_Relations_Program': 'Open',
    'Classified_Project_Blueprints': 'Top Secret',
    'Executive_Decision_Memo': 'Top Secret',
    'High_Level_Strategy_Document': 'Top Secret',
    'Security_Breach_Incident_Report': 'Top Secret',
    'Classified_R&D_Findings': 'Top Secret',
    'Crisis_Response_Plan': 'Top Secret',
    'Sensitive_Customer_Communications': 'Top Secret',
    'CEO_Private_Memos': 'Top Secret',
    'National_Security_Briefing_Notes': 'Top Secret',
    'Classified_Personnel_Dossiers': 'Top Secret',
    'Intellectual_Property_Patents': 'Top Secret',
    'Security_Clearance_Procedures': 'Top Secret',
    'Black_Ops_Mission_Documents': 'Top Secret',
    'Encryption_Algorithm_Specifications': 'Top Secret',
    'Classified_Military_Contracts': 'Top Secret',
    'Stealth_Technology_Plans': 'Top Secret',
    'Classified_Market_Intelligence_Reports': 'Top Secret',
    'Undercover_Operative_Identities': 'Top Secret',
    'Top_Secret_Surveillance_Logs': 'Top Secret',
    'Confidential_Asset_Location_Maps': 'Top Secret',
    'Sensitive_Cybersecurity_Protocols': 'Top Secret',
    'Nuclear_Arms_Control_Agreements': 'Top Secret',
    'Black_Hat_Hacker_Dossier': 'Top Secret',
    'Classified_Spy_Mission_Debriefings': 'Top Secret',
    'Classified_Government_Agency_Plans': 'Top Secret',
    'Decryption_Key_Registry': 'Top Secret',
    'Top_Secret_Undercover_Operations_Manual': 'Top Secret',
    'Classified_Alien_Encounter_Reports': 'Top Secret',
    'Special_Forces_Tactical_Playbook': 'Top Secret',
    'Confidential_War_Game_Scenarios': 'Top Secret',
    'Confidential_Client_List': 'Sensitive',
    'Employee_Salary_Details': 'Sensitive',
    'Internal_Memo_on_Layoffs': 'Sensitive',
    'Proprietary_Product_Designs': 'Sensitive',
    'Confidential_Contract_Negotiations': 'Sensitive',
    'Sensitive_Market_Analysis': 'Sensitive',
    'Strategic_Partnership_Agreement': 'Sensitive',
    'Restricted_Access_Protocol': 'Sensitive',
    'Sensitive_Supplier_Contacts': 'Sensitive',
    'Confidential_Merger_Acquisition_Plans': 'Sensitive',
    'Non-Disclosure_Agreements': 'Sensitive',
    'Sensitive_Customer_Satisfaction_Data': 'Sensitive',
    'Private_Investment_Proposals': 'Sensitive',
    'Classified_Personnel_Records': 'Sensitive',
    'Highly_Confidential_Board_Meeting_Minutes': 'Sensitive',
    'Sensitive_Intellectual_Property_Portfolio': 'Sensitive',
    'Executive_Compensation_Details': 'Sensitive',
    'Key_Client_Relationship_Management_Strategy': 'Sensitive',
    'Confidential_Competitive_Analysis': 'Sensitive',
    'Internal_Restructuring_Plan': 'Sensitive',
    'Sensitive_Business_Development_Strategy': 'Sensitive',
    'Restricted_Access_Server_Logs': 'Sensitive',
    'Proprietary_Software_Source_Code': 'Sensitive',
    'Confidential_Marketing_Strategy': 'Sensitive',
    'Sensitive_Supplier_Negotiations': 'Sensitive',
    'High-Level_Business_Proposals': 'Sensitive',
    'Classified_Financial_Forecasts': 'Sensitive',
    'Internal_Investment_Memo': 'Sensitive',
    'Sensitive_Research_Data': 'Sensitive',
    'High-Risk_Account_Review': 'Sensitive',
    'Financial_Statements_2024': 'Open',
    'Marketing_Plan': 'Open',
    'Company_Policy_Manual': 'Open',
    'Quarterly_Earnings_Report': 'Open',
    'Employee_Satisfaction_Survey': 'Open',
    'Sales_Forecast': 'Open',
    'Meeting_Minutes_January': 'Open',
    'Product_Brochure': 'Open',
    'Press_Release': 'Open',
    'Training_Module': 'Open',
    'Salary_Scale_Guidelines': 'Open',
    'Company_Newsletter': 'Open',
    'Team_Building_Activities': 'Open',
    'Customer_Testimonials': 'Open',
    'Vendor_Profiles': 'Open',
    'Industry_Research': 'Open',
    'Training_Schedule': 'Open',
    'Corporate_Social_Responsibility_Report': 'Open',
    'Event_Calendar': 'Open',
    'Product_Demonstration_Video': 'Open',
    'Office_Policy_Memo': 'Open',
    'Community_Outreach_Initiatives': 'Open',
    'Marketing_Campaign_Overview': 'Open',
    'Company_Culture_Statement': 'Open',
    'Employee_News_Bulletin': 'Open',
    'Performance_Incentive_Program': 'Open',
    'New_Product_Release_Announcement': 'Open',
    'Customer_Service_Policy': 'Open',
    'Team_Building_Workshop_Materials': 'Open',
    'Employee_Handbook': 'Sensitive',
    'Customer_Database_Backup': 'Sensitive',
    'Confidential_Market_Analysis': 'Sensitive',
    'Executive_Compensation_Plan': 'Sensitive',
    'Project_Budget': 'Sensitive',
    'Intellectual_Property_Disclosure': 'Sensitive',
    'Internal_Audit_Report': 'Sensitive',
    'Sensitive_Product_Designs': 'Sensitive',
    'Legal_Contracts': 'Sensitive',
    'Client_Confidentiality_Agreement': 'Sensitive',
    'Employee_Performance_Reviews': 'Sensitive',
    'Sensitive_Company_Strategy': 'Sensitive',
    'Research_and_Development_Plan': 'Sensitive',
    'Sensitive_Inventory_List': 'Sensitive',
    'Proprietary_Technology_Documentation': 'Sensitive',
    'Business_Plan_Details': 'Sensitive',
    'Sensitive_Customer_Data': 'Sensitive',
    'Executive_Meeting_Notes': 'Sensitive',
    'Corporate_Partnership_Agreement': 'Sensitive',
    'Classified_Project_Blueprints': 'Top Secret',
    'Executive_Decision_Memo': 'Top Secret',
    'High_Level_Strategy_Document': 'Top Secret',
    'Security_Breach_Incident_Report': 'Top Secret',
    'Classified_R&D_Findings': 'Top Secret',
    'Crisis_Response_Plan': 'Top Secret',
    'Sensitive_Customer_Communications': 'Top Secret',
    'CEO_Private_Memos': 'Top Secret',
    'National_Security_Briefing_Notes': 'Top Secret',
    'Classified_Personnel_Dossiers': 'Top Secret',
    'Intellectual_Property_Patents': 'Top Secret',
    'Security_Clearance_Procedures': 'Top Secret',
    'Black_Ops_Mission_Documents': 'Top Secret',
    'Encryption_Algorithm_Specifications': 'Top Secret',
    'Classified_Military_Contracts': 'Top Secret',
    'Stealth_Technology_Plans': 'Top Secret',
    'Classified_Market_Intelligence_Reports': 'Top Secret',
    'Undercover_Operative_Identities': 'Top Secret',
    'Top_Secret_Surveillance_Logs': 'Top Secret',
    'Confidential_Asset_Location_Maps': 'Top Secret',
    'Sensitive_Cybersecurity_Protocols': 'Top Secret',
    'Nuclear_Arms_Control_Agreements': 'Top Secret',
    'Black_Hat_Hacker_Dossier': 'Top Secret',
    'Classified_Spy_Mission_Debriefings': 'Top Secret',
    'Classified_Government_Agency_Plans': 'Top Secret',
    'Decryption_Key_Registry': 'Top Secret',
    'Top_Secret_Undercover_Operations_Manual': 'Top Secret',
    'Classified_Alien_Encounter_Reports': 'Top Secret',
    'Special_Forces_Tactical_Playbook': 'Top Secret',
    'Confidential_War_Game_Scenarios': 'Top Secret'
    }

def shuffle_dictionary(dictionary):
    """
    Shuffle the entries in the dictionary randomly.

    Parameters:
    - dictionary: dict, the dictionary to be shuffled.

    Returns:
    - shuffled_dict: dict, the shuffled dictionary.
    """
    shuffled_keys = list(dictionary.keys())
    random.shuffle(shuffled_keys)
    shuffled_dict = {key: dictionary[key] for key in shuffled_keys}
    return shuffled_dict

print(shuffle_dictionary(file_data))