runtime: python

env: flex

entrypoint: gunicorn -b :8080 --worker-class eventler -w 4 app:app

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.12"

manual_scaling:
  instances: 4

network:
  session_affinity: true
