example_data = {
    "Confidential report on quarterly financial performance.": "Top Secret",
    "Minutes of the team brainstorming session.": "Sensitive",
    "Public announcement about the company's charity initiative.": "Open",
    "Financial forecasts for the next fiscal year.": "Sensitive",
    "Project roadmap for the upcoming software release.": "Top Secret",
    "Employee handbook for remote work policies.": "Top Secret",
    "Agenda for the company-wide town hall meeting.": "Sensitive",
    "Draft of the press release for a strategic partnership.": "Open",
    "Security guidelines for remote data access.": "Top Secret",
    "Employee performance evaluations for the current quarter.": "Sensitive",
    "Customer service guidelines for handling inquiries.": "Open",
    "Proposal for cost-cutting measures.": "Sensitive",
    "Publicly available product user manual.": "Open",
    "Internal email communication about team building.": "Open",
    "Draft of the company's social media policy.": "Sensitive",
    "Research paper on industry trends.": "Sensitive",
    "Publicly shared slide deck for a company presentation.": "Open",
    "Company-wide email about office maintenance.": "Sensitive",
    "Marketing brochure for a public event.": "Open",
    "Newsletter containing updates on company achievements.": "Sensitive",
    "Confidential research report on market trends.": "Top Secret",
    "Meeting minutes for the project kickoff.": "Sensitive",
    "Public announcement about the company's community service program.": "Open",
    "Financial projections for the upcoming fiscal year.": "Sensitive",
    "Development plan for a new software application.": "Top Secret",
    "Employee handbook outlining workplace safety policies.": "Top Secret",
    "Agenda for the annual company retreat.": "Sensitive",
    "Draft of the press release for a product launch event.": "Open",
    "Security protocols for network access control.": "Top Secret",
    "Employee performance assessments for the current quarter.": "Sensitive",
    "Guidelines for managing customer feedback.": "Open",
    "Proposal for implementing flexible work hours.": "Sensitive",
    "User manual for a new product available to the public.": "Open",
    "Internal memo about team collaboration activities.": "Open",
    "Draft of the company's social media engagement strategy.": "Sensitive",
    "Research paper on sustainable business practices.": "Sensitive",
    "Presentation slides for a public webinar.": "Open",
    "Company-wide email about upcoming office renovations.": "Sensitive",
    "Marketing brochure for a new service offering.": "Open",
    "Newsletter containing updates on company achievements and milestones.": "Sensitive",
    "Draft of the company's quarterly financial report.": "Top Secret",
    "Team retrospective meeting notes.": "Sensitive",
    "Public announcement about the company's sustainability efforts.": "Open",
    "Financial analysis for the upcoming budget.": "Sensitive",
    "Roadmap for product feature enhancements.": "Top Secret",
    "Employee handbook update for health and safety policies.": "Top Secret",
    "Agenda for the team-building offsite.": "Sensitive",
    "Draft of the press release for an industry award.": "Open",
    "Cybersecurity guidelines for protecting sensitive information.": "Top Secret",
    "Employee training program evaluations for the current quarter.": "Sensitive",
    "Guidelines for handling escalated customer complaints.": "Open",
    "Proposal for implementing a mentorship program.": "Sensitive",
    "User manual for an upcoming software upgrade.": "Open",
    "Internal email communication about office holiday party.": "Open",
    "Draft of the company's social media advertising strategy.": "Sensitive",
    "Research paper on the impact of technology on business.": "Sensitive",
    "Publicly shared presentation slides for a product demo.": "Open",
    "Company-wide email about new workplace policies.": "Sensitive",
    "Marketing campaign materials for an upcoming promotion.": "Open",
    "Newsletter featuring company news and employee achievements.": "Sensitive",
    "Sensitive customer data protection guidelines.": "Top Secret",
    "Meeting minutes for the product launch planning session.": "Sensitive",
    "Public announcement about the company's diversity and inclusion initiative.": "Open",
    "Financial projections for the next fiscal quarter.": "Sensitive",
    "Development plan for a mobile application.": "Top Secret",
    "Employee handbook outlining code of conduct policies.": "Top Secret",
    "Agenda for the departmental strategy session.": "Sensitive",
    "Draft of the press release for a partnership with a nonprofit.": "Open",
    "Security protocols for secure file sharing.": "Top Secret",
    "Employee performance assessments for the current quarter.": "Sensitive",
    "Guidelines for managing customer feedback on social media.": "Open",
    "Proposal for implementing flexible work hours.": "Sensitive",
    "User manual for a new hardware product.": "Open",
    "Internal memo about team collaboration initiatives.": "Open",
    "Draft of the company's social responsibility report.": "Sensitive",
    "Research paper on the future of renewable energy.": "Sensitive",
    "Publicly shared presentation slides for a company webinar.": "Open",
    "Company-wide email about office security measures.": "Sensitive",
    "Marketing brochure for an upcoming product launch.": "Open",
    "Newsletter containing updates on company milestones.": "Sensitive",
    "Confidential patent application for a new invention.": "Top Secret",
    "Meeting minutes for the strategic planning retreat.": "Sensitive",
    "Public announcement about the company's educational outreach program.": "Open",
    "Financial forecasts for the upcoming fiscal year.": "Sensitive",
    "Development plan for a cloud-based software solution.": "Top Secret",
    "Employee handbook outlining remote work best practices.": "Top Secret",
    "Agenda for the annual company picnic.": "Sensitive",
    "Draft of the press release for an upcoming product feature.": "Open",
    "Security guidelines for securing customer accounts.": "Top Secret",
    "Employee training program assessments for the current quarter.": "Sensitive",
    "Guidelines for managing sensitive data during product launches.": "Open",
    "Proposal for implementing employee recognition programs.": "Sensitive",
    "User manual for a new software tool available to the public.": "Open",
    "Internal communication about team-building activities.": "Open",
    "Draft of the company's social media content strategy.": "Sensitive",
    "Research paper on the impact of artificial intelligence on industries.": "Sensitive",
    "Presentation slides for a public webinar on emerging technologies.": "Open",
    "Company-wide email about updates to the office layout.": "Sensitive",
    "Marketing brochure for an upcoming service enhancement.": "Open",
    "Newsletter containing updates on company achievements and employee milestones.": "Sensitive",
    "confidential.": "Top Secret",
    "Medical Records.": "Top Secret",
    "Personal Information of employees": "Top Secret",
    "Roadmap of production": "Top Secret",
    "upcoming new software feature": "Top Secret",
}